version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=jonasdeyvid_Sistema-Loca-Carros-2.0 -Dsonar.organization=jonasdeyvid -Dsonar.host.url=https://sonarcloud.io

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
